name: Deploy Supabase Edge Functions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show repo tree
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "---- supabase dir ----"
          ls -la supabase || true
          echo "---- functions dir ----"
          ls -la supabase/functions || true

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy all functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          supabase functions deploy --project-ref "$SUPABASE_PROJECT_REF" --no-verify-jwt --all
