name: Deploy Supabase Edge Functions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Use the Supabase CLI Docker image in CI (no local install needed)
      - name: Deploy all functions to Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          docker run --rm \
            -e SUPABASE_ACCESS_TOKEN \
            -e SUPABASE_PROJECT_REF \
            -v "$PWD":/workspace -w /workspace \
            supabase/cli:latest \
            supabase functions deploy --project-ref "$SUPABASE_PROJECT_REF" --no-verify-jwt --all
